name: schedule_generator_with_gemini
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  http: ^1.3.0
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.8.0
  google_generative_ai: ^0.4.6
  shimmer: ^3.0.0
  device_preview: ^1.2.0

flutter:
  uses-material-design: true
